"""Overlay high-margin commercial fields and executive pitches onto prospects."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CURATED = ROOT / "data" / "prospects.json"

AGENCY = {
    "name": "SAP Desk",
    "wedge": "Named 90-day S/4 workstream, billed as consulting — never a CV into a black hole",
    "markets": ["India", "Germany"],
    "offer": [
        "10-day S/4 slip diagnostic — ₹2.8L / €4,500 fixed (findings + 90-day proposal)",
        "90-day named workstream on the client SOW — India ₹3.2–6.5L/month, Germany €950–1,200/day",
        "Post-go-live plant hypercare pod (2 people) — ₹5.5–7L/month retainer",
    ],
    "do_not_pitch_yet": [
        "Perm placement at 8–12% CTC (one-time, recruiter race, bad margin)",
        "SI subcontracting at 8–15% markup (they own the client and squeeze you)",
        "Free health checks (trains buyers that your time is worth nothing)",
        "Prime SI for a Fortune-500 greenfield",
    ],
    "products": [
        {
            "id": "diagnostic",
            "name": "10-day S/4 slip diagnostic",
            "price": "₹2.8 Lakh / €4,500 fixed",
            "margin": "65–75%",
            "when": "End-client with an open SAP req or a recent go-live. You need a paid door, not a free chat.",
            "close": "PO or 50% advance. Written findings on day 10. Convert to 90-day SOW.",
        },
        {
            "id": "workstream_in",
            "name": "90-day named workstream (India)",
            "price": "₹3.2–4.5L/mo functional · ₹4.5–6.5L/mo integration/architect",
            "margin": "40–50% if you pay the consultant 55–60% of bill",
            "when": "Tata, Bosch, Siemens Energy, Airbus — they are already hiring, so the workstream is late.",
            "close": "Named person, start date, 10-day replacement, conversion to FTE = 8% residual (not 15%).",
        },
        {
            "id": "arbeitspaket",
            "name": "S/4 Arbeitspaket (Germany)",
            "price": "€950–1,200 / day billed",
            "margin": "20–35% on a DE freelancer · 45–55% if CET delivery from India is accepted",
            "when": "Brownfield PM, CO greenfield, remote SD/OTC. Sell the Arbeitspaket, not a CV.",
            "close": "Honorarvertrag / SOW, 3-month minimum, 10-day notice after month one.",
        },
        {
            "id": "hypercare",
            "name": "Plant hypercare retainer",
            "price": "₹5.5–7 Lakh / month for a 2-person pod",
            "margin": "45%+",
            "when": "Grasim / Birla Opus and any plant that went live in the last 6 months.",
            "close": "90-day minimum, ticket + defect backlog, no new-implementation pitch.",
        },
    ],
}

STRATEGY = {
    "best_channel": "economic_buyer_workstream",
    "why": "Recruiters buy CVs at commodity margin. Programme managers buy a named person on a SOW because the S/4 seat has been empty for weeks. That is consulting gross margin, not a staffing fee.",
    "rank": [
        "India end-client workstream (Tata Electronics, Bosch, Siemens Energy, Airbus) — talk to SAP programme / IT, not TA",
        "Post-go-live retainer (Grasim / Birla Opus) — highest Indian lifetime value",
        "German Arbeitspaket at €950–1,200/day (teamative, FERCHAU, remote SD)",
        "IGGL specialist project only if you can actually integrate S/4 × GSP this week",
        "Ignore SI perm reqs unless they take a 90-day SOW at your rate card",
    ],
    "pitch_rules": [
        "One observation about their delay. One commercial. One ask. Stop talking.",
        "Never attach a CV to the first note. CVs make you a recruiter. A SOW makes you a vendor.",
        "Name the price. Vague 'let us discuss' gets you trained down.",
        "Talk to the person who owns the slip. TA is a back door, not the buyer.",
        "If they want perm only, walk. Conversion fee 8% after 90 days is the concession, not the opener.",
    ],
}

# margin: send | later | skip
OVERLAYS = {
    "P001": {
        "margin": "send",
        "gross": "project 35–50% if you deliver; skip if you only want a vendor-list stamp",
        "product": "diagnostic",
        "talk_to": "GM C&P (already have email) + IGGL SAP / IT lead",
        "price_anchor": "Bid as SAP integration specialist with a GSTN-authorised GSP — do not discount to win a PSU race",
        "linkedin_people_override": "https://www.linkedin.com/search/results/people/?keywords=IGGL%20SAP%20OR%20%22information%20technology%22%20Guwahati",
        "linkedin_note": "Mr. Talukdar — IGGL-100126 is a 60-day S/4 × GSP e-invoice integration, not a staffing req. We bid as the SAP integration arm with a GSTN-authorised GSP, fixed scope, no body shopping. I can send the one-page capability + CPP status today. If the window is shut, keep us for the next AMS package — IGGL already cycles SAP support. — [Your name], SAP Desk",
        "email_subject": "IGGL-100126 — fixed-scope S/4 × GSP integration (not a staffing bid)",
        "email_body": "Dear Mr. Talukdar,\n\nTender IGGL-100126 closes 7 September 2026. You need SAP S/4HANA Private Cloud talking to a GSTN-authorised GSP for e-invoicing — in 60 days.\n\nWe will not send CVs. We will bid, or partner a GSP and own the SAP integration workstream, at a fixed scope. That is how this finishes on time.\n\nI can send a one-page capability note and our CPP/DSC status today. If we are late for this NIT, please keep SAP Desk on the list for the next AMS / enhancement package.\n\nRegards,\n[Your name]\n[Mobile] | [Email]\nSAP Desk",
        "followup_2": "Mr. Talukdar — 48 hours to bid close on IGGL-100126. Capability note is ready. Shall I send it to C&P or is the file already full?",
        "followup_3": "Closing my file on IGGL-100126. If a later SAP AMS or e-invoice defect package comes up, cnp.department@iggl.co.in has this thread.",
        "call_opener": "I will be 90 seconds. You have a 60-day S/4–GSP integration. Staffing will miss it. We bid fixed scope with a GSTN GSP. Do you still have a slot for a specialist, or is the SI already chosen?",
    },
    "P002": {
        "margin": "send",
        "gross": "40–50% on a 90-day SOW",
        "product": "workstream_in",
        "talk_to": "SAP programme / IT manufacturing lead; TA (Saral Christy) only as the door",
        "price_anchor": "₹3.8L / month named SD/MM lead, 90 days, on-site Bengaluru",
        "linkedin_people_override": "https://www.linkedin.com/search/results/people/?keywords=%22Tata%20Electronics%22%20(SAP%20OR%20S%2F4)%20(program%20OR%20%22IT%20head%22%20OR%20manufacturing)",
        "linkedin_note": "You are hiring an on-site S/4 SD/MM lead for the foundry. That posting usually means OTC/PTP at the plant is slipping while TA runs a 40-day cycle. I do not send perm CVs. I put a named SD/MM lead on a 90-day SOW, on-site, ₹3.8L/month, replaced in 10 days if it is the wrong fit. 15 minutes this week if the seat is still empty. — [Your name], SAP Desk",
        "email_subject": "Tata Electronics — 90-day S/4 SD/MM workstream at ₹3.8L/mo, not a perm CV",
        "email_body": "Hello,\n\nTata Electronics is hiring an on-site S/4HANA SD/MM lead (subcontracting, STOs, plant + warehouse). While that req sits open, the workstream is late.\n\nOffer: one named SD/MM consultant, 90-day SOW, on-site Bengaluru / Hosur, ₹3.8 lakh per month. 10-day replacement. If you later convert to FTE, conversion is 8% of annual CTC — not a 15% recruiter fee up front.\n\nI will not attach CVs to this mail. If the seat is empty, give me 15 minutes and I will name the person and the start date.\n\nRegards,\n[Your name] | SAP Desk\n[Mobile]",
        "followup_2": "Still seeing the SD/MM lead open. A 90-day SOW at ₹3.8L/mo is cheaper than another month of a dark workstream. Thursday 15 min — yes or no?",
        "followup_3": "I will assume the foundry SAP seat is covered. Stopping the chase. If a plant hypercare pod is useful after go-live, reply 'pod'.",
        "call_opener": "Blunt version: an empty senior S/4 seat for three weeks costs more than my 90-day SOW. I have one SD/MM who can start. Two minutes on the commercial, then you decide.",
    },
    "P003": {
        "margin": "send",
        "gross": "40–50% on a 90-day SOW",
        "product": "workstream_in",
        "talk_to": "SAP CoE / PP or EWM process owner at BGSW — not general TA",
        "price_anchor": "₹4.2L/mo PP-DS or EWM named consultant, 90 days",
        "linkedin_people_override": "https://www.linkedin.com/search/results/people/?keywords=BGSW%20OR%20%22Bosch%20Global%20Software%22%20(SAP%20OR%20PP%2FDS%20OR%20EWM)%20(lead%20OR%20manager%20OR%20architect)",
        "linkedin_note": "BGSW is hiring S/4 PP (M2S / PP-DS) and I2D EWM in Bengaluru. Two reqs means a template rollout is under-staffed, not that HR needs more CVs. I put a named PP-DS or EWM consultant on a 90-day SOW at ₹4.2L/month, EU-overlap hours, 10-day replacement. 15 min if either seat is still empty. — [Your name], SAP Desk",
        "email_subject": "BGSW — 90-day PP-DS / EWM workstream at ₹4.2L/mo",
        "email_body": "Hello,\n\nBGSW has open S/4 Manufacture-to-Stock (PP / embedded PP-DS) and I2D EWM seats. That is a rollout gap, not a campus hire.\n\nOffer: one named consultant per skill, 90-day SOW, Bengaluru, ₹4.2 lakh per month, EU stand-up overlap, 10-day replacement. No perm campaign. No CV pack until we agree the SOW.\n\nWhich workstream is slipping — PP-DS or warehouse?\n\nRegards,\n[Your name] | SAP Desk\n[Mobile]",
        "followup_2": "PP-DS and I2D EWM still on the board. I can name one person this week on a 90-day SOW. Who owns the template — CoE or TA?",
        "followup_3": "Closing this thread. If a later rollout wave needs a 90-day PP or EWM seat, reply with the module.",
        "call_opener": "You have two SAP seats open on a global template. I sell a 90-day named consultant at ₹4.2L, not a perm funnel. Which module is actually late?",
    },
    "P004": {
        "margin": "send",
        "gross": "45–55% on integration/MDG (scarce)",
        "product": "workstream_in",
        "talk_to": "Digital Process Transformation / SAP CoE lead — they already hire internal + external",
        "price_anchor": "₹5.5L/mo Integration or MDG lead · ₹4.2L/mo FICO · 90-day SOW",
        "linkedin_people_override": "https://www.linkedin.com/search/results/people/?keywords=%22Siemens%20Energy%22%20India%20(%22Digital%20Process%20Transformation%22%20OR%20SAP)%20(Lead%20OR%20Head%20OR%20Architect)",
        "linkedin_note": "Siemens Energy India is hiring Integration, MDG, FICO and ABAP/BTP on the same S/4 programme. Four reqs is a CoE that is behind, not a recruiting problem. I feed the CoE with named 90-day SOWs — Integration or MDG at ₹5.5L/month — I do not replace you as SI. 15 min on which workstream is red. — [Your name], SAP Desk",
        "email_subject": "Siemens Energy S/4 — named Integration/MDG workstream at ₹5.5L/mo",
        "email_body": "Hello,\n\nDigital Process Transformation is hiring an Integration Lead, FICO BSA, MDG migration expert, and ABAP/BTP Development Lead in India at the same time. That is a red programme, not four unrelated jobs.\n\nI will not spray CVs at TA. Offer: one named Integration or MDG lead on a 90-day SOW at ₹5.5 lakh per month, or FICO at ₹4.2 lakh, 10-day replacement, we work under your CoE.\n\nWhich of the four is actually holding the cutover?\n\nRegards,\n[Your name] | SAP Desk\n[Mobile]",
        "followup_2": "Four SAP seats still advertised. I can put an Integration or MDG lead on a 90-day SOW this month. Who in DPT owns vendor SOWs — not the recruiter?",
        "followup_3": "Stopping. If a workstream goes red before cutover, reply with Integration / MDG / FICO / ABAP.",
        "call_opener": "Four parallel SAP hires means the conversion is slipping. I sell a named 90-day lead under your CoE at ₹5.5L. Which stream is red?",
    },
    "P005": {
        "margin": "send",
        "gross": "40–50% on a 90-day SOW",
        "product": "workstream_in",
        "talk_to": "Application Services / SAP manufacturing IT, Bengaluru",
        "price_anchor": "₹3.6L/mo S/4 MM + migration cockpit, 90 days",
        "linkedin_people_override": "https://www.linkedin.com/search/results/people/?keywords=Airbus%20Bengaluru%20(SAP%20OR%20S%2F4)%20(MM%20OR%20%22application%20services%22)%20(manager%20OR%20lead)",
        "linkedin_note": "Airbus Bengaluru is hiring S/4 MM with LTMC and PP integration for aircraft manufacturing. That is master-data risk on a production landscape. Named MM consultant, 90-day SOW, ₹3.6L/month, not a perm CV. 15 min if the seat is empty. — [Your name], SAP Desk",
        "email_subject": "Airbus Bengaluru — 90-day S/4 MM workstream at ₹3.6L/mo",
        "email_body": "Hello,\n\nAirbus India is hiring an S/4 MM consultant (LTMC/LSMW, Business Partner, PP integration) in Bengaluru. Master data on a manufacturing system is not a role you want vacant.\n\nOffer: named MM consultant, 90-day SOW, ₹3.6 lakh per month, 10-day replacement. CVs after we agree the SOW.\n\nIs the blocker TA, or do you need a person on the system next week?\n\nRegards,\n[Your name] | SAP Desk\n[Mobile]",
        "followup_2": "MM seat still listed. ₹3.6L/mo for 90 days vs another month of migration-cockpit delay. 15 min — yes or no?",
        "followup_3": "Closing. Reply 'MM' if the manufacturing application team wants a named contractor later.",
        "call_opener": "S/4 MM with LTMC on aircraft manufacturing is a cutover risk. I have a named 90-day SOW at ₹3.6L. Do you want the person or more CVs?",
    },
    "P006": {
        "margin": "send",
        "gross": "45%+ recurring — best India lifetime value",
        "product": "hypercare",
        "talk_to": "IT head / SAP / SCM systems owner at Grasim or Birla Opus — not campus TA",
        "price_anchor": "₹6.2L/mo for a 2-person EWM + S/4 hypercare pod, 90-day minimum",
        "linkedin_people_override": "https://www.linkedin.com/search/results/people/?keywords=(Grasim%20OR%20%22Birla%20Opus%22%20OR%20%22Aditya%20Birla%20Chemicals%22)%20(SAP%20OR%20EWM)%20(head%20OR%20CIO%20OR%20%22IT%22)",
        "linkedin_note": "Grasim / Birla Opus just went live on S/4 + EWM. The SI will demobilise. Plants will still have warehouse defects and a rollout backlog. I do not pitch another implementation. I sell a 2-person hypercare pod at ₹6.2L/month, 90 days, defect + backlog only. 15 min with whoever owns AMS. — [Your name], SAP Desk",
        "email_subject": "Birla Opus / Grasim — 90-day EWM hypercare pod at ₹6.2L/mo",
        "email_body": "Hello,\n\nAfter an S/4 + EWM go-live, the expensive partner leaves and the plants keep the tickets. That gap is where we work.\n\nOffer: two-person pod (EWM + S/4), ₹6.2 lakh per month, 90-day minimum. Defects, backlog, next-warehouse rollout support. No greenfield pitch.\n\nIf useful, a 10-day paid diagnostic at ₹2.8 lakh will list the actual backlog before the pod starts.\n\nWho owns AMS now — internal IT or the SI that is already leaving?\n\nRegards,\n[Your name] | SAP Desk\n[Mobile]",
        "followup_2": "SIs usually exit 6–10 weeks after go-live. If your AMS bench is already thin, the ₹6.2L pod is cheaper than a missed dispatch window. Who owns warehouse IT?",
        "followup_3": "I will assume Stellium / the SI still owns hypercare. Stopping. Reply 'pod' if a plant goes red.",
        "call_opener": "You went live. The SI is leaving. I sell a 90-day EWM hypercare pod at ₹6.2L, not a new project. Is AMS already sold, or is it a hole?",
    },
    "P007": {
        "margin": "skip",
        "gross": "8–15% — they own the client",
        "product": "workstream_in",
        "talk_to": "skip unless they accept your rate card on a 90-day SOW",
        "price_anchor": "Only if billed ≥ ₹3.4L/mo to NTT — otherwise walk",
        "linkedin_note": "SKIP — NTT will take CVs and pay a staffing markup. Do not train the market that you are cheap overflow. Exception: they sign your 90-day SOW at ₹3.4L+.",
        "email_subject": "SKIP",
        "email_body": "Do not send.",
        "followup_2": "",
        "followup_3": "",
        "call_opener": "",
    },
    "P008": {
        "margin": "later",
        "gross": "medium only on EU-overlap contract at your card",
        "product": "arbeitspaket",
        "talk_to": "India delivery lead / partner — not TA",
        "price_anchor": "₹4.0L/mo PP or EWM, EU overlap, 6-month SOW — no perm",
        "linkedin_people_override": "https://www.linkedin.com/search/results/people/?keywords=BearingPoint%20India%20SAP%20(Partner%20OR%20%22delivery%22%20OR%20%22S%2F4%22)",
        "linkedin_note": "BearingPoint India is hiring PP/EWM for sold offshore S/4 rollouts. I do not fill perm reqs. If a billed project has an empty seat, I will put a named PP or EWM on a 6-month SOW at ₹4.0L/month with EU overlap. If this is a speculative hire, ignore. — [Your name], SAP Desk",
        "email_subject": "BearingPoint — named PP/EWM on a 6-month SOW at ₹4.0L, not perm",
        "email_body": "Hello,\n\nYou are hiring PP and EWM in Bengaluru for international S/4 rollouts.\n\nI only engage if this is a sold, billed project with a vacant seat. Offer: named consultant, 6-month SOW, ₹4.0 lakh per month, EU overlap, 10-day replacement.\n\nIf TA is building a bench, this is not for you.\n\nRegards,\n[Your name] | SAP Desk",
        "followup_2": "Only chasing if a rollout seat is empty on a billed project. ₹4.0L/mo SOW. Yes or no?",
        "followup_3": "Stopping. I do not join perm funnels.",
        "call_opener": "Is this a billed empty seat or a bench hire? I only do the first, at ₹4.0L on a 6-month SOW.",
    },
    "P009": {
        "margin": "skip",
        "gross": "commodity ABAP",
        "product": "workstream_in",
        "talk_to": "skip",
        "price_anchor": "skip",
        "linkedin_note": "SKIP — Genpact ABAP perm/contract at SI rates. Low margin, slow pay.",
        "email_subject": "SKIP",
        "email_body": "Do not send.",
        "followup_2": "",
        "followup_3": "",
        "call_opener": "",
    },
    "P010": {
        "margin": "later",
        "gross": "only if you reach the end-client behind the 120-company-code brownfield",
        "product": "workstream_in",
        "talk_to": "Ask who the end client is — that is the high-margin buyer",
        "price_anchor": "Do not sell CO at recruiter rates. Find the programme owner.",
        "linkedin_people_override": "https://www.linkedin.com/search/results/people/?keywords=ADV%20TECHMINDS%20SAP%20(CO%20OR%20S%2F4)%20(director%20OR%20partner)",
        "linkedin_note": "You are hiring CO for a 120-company-code brownfield. That programme will bleed FI, data and SIT for 18 months. I will not dump a CO CV at a staffing desk. Introduce me to the programme owner and I will price a 90-day CO workstream at ₹4.5L/month. If you cannot make that intro, we stop. — [Your name], SAP Desk",
        "email_subject": "120-company-code brownfield — I need the programme owner, not the req",
        "email_body": "Hello,\n\nA 120-legal-entity ECC→S/4 brownfield is a programme, not a single CO hire.\n\nI price a named CO workstream at ₹4.5 lakh per month for 90 days to the end client or the SI partner who owns delivery. I do not work as an anonymous CV source.\n\nCan you introduce the programme manager? If not, please do not forward this to a general mailbox.\n\nRegards,\n[Your name] | SAP Desk",
        "followup_2": "Still only useful if I can speak to the programme owner. One intro, or I close.",
        "followup_3": "Closing. Without the economic buyer this is a staffing race.",
        "call_opener": "Who is the end client on the 120-company-code conversion? If you cannot say, I cannot price a workstream.",
    },
    "P011": {
        "margin": "skip",
        "gross": "TCS vendor cycle kills margin",
        "product": "workstream_in",
        "talk_to": "skip",
        "price_anchor": "skip",
        "linkedin_note": "SKIP — TCS empanelment is a six-month job for a thin markup.",
        "email_subject": "SKIP",
        "email_body": "Do not send.",
        "followup_2": "",
        "followup_3": "",
        "call_opener": "",
    },
    "P012": {
        "margin": "send",
        "gross": "20–35% on DE PL · 45%+ if they buy India PMO/SIT factory under their PL",
        "product": "arbeitspaket",
        "talk_to": "teamative delivery + the Auftraggeber-side PM if you can get the name",
        "price_anchor": "DE PL €1,150/day · or PMO/SIT factory €620/day blended from India",
        "linkedin_people_override": "https://www.linkedin.com/search/results/people/?keywords=teamative%20(SAP%20OR%20S%2F4)%20(Partner%20OR%20%22Business%20Development%22%20OR%20Recruiter)",
        "linkedin_note": "Euer Brownfield-PL (Ulm, 24 Monate, Auftraggeber Handel, Start 01.10.) ist ein Arbeitspaket, kein CV-Versand. Option A: deutschsprachiger S/4-PL zu €1.150/Tag. Option B: euer PL bleibt, wir liefern PMO + SIT aus Indien zu €620/Tag blended. 15 Minuten, dann ein Profil — nicht vorher. — [Your name], SAP Desk",
        "email_subject": "Ulm Brownfield — €1.150/Tag PL oder €620/Tag PMO-Factory, kein CV-Ping",
        "email_body": "Hallo,\n\nMandat: S/4 Projektleiter Brownfield, 24 Monate, Ulm 50/50, Start 01.10.2026, Auftraggeberseite Handel.\n\nIch schicke kein CV in die Börse.\n\nA — deutschsprachiger PL, €1.150 / Tag, 3 Monate Mindestlaufzeit.\nB — euer PL bleibt; PMO, Daten, SIT aus Indien, €620 / Tag blended, deutschsprachige Steuerung.\n\nWelche Variante soll ich in einem zweiseitigen Angebot ausarbeiten? 15 Minuten genügen.\n\nMit freundlichen Grüßen\n[Your name] | SAP Desk\n[Mobile]",
        "followup_2": "Start 1. Oktober. Ohne PL oder PMO-Factory rutscht der Brownfield. A €1.150 oder B €620 — welche Zahl darf ich festziehen?",
        "followup_3": "Ich schließe die Akte. Wenn der PL abspringt, reicht ein Wort: A oder B.",
        "call_opener": "Zwei Zahlen: €1.150 für einen deutschsprachigen PL, €620 für die Factory unter eurem PL. Welches Problem habt ihr wirklich — den PL oder die Testbandbreite?",
    },
    "P013": {
        "margin": "send",
        "gross": "25–35% on scarce S/4 CO + UPA",
        "product": "arbeitspaket",
        "talk_to": "Melina Wittwer, then the end-client CO lead if they will intro",
        "price_anchor": "€1,100/day S/4 CO (UPA / ML / Margin Analysis), German required unless they waive it",
        "linkedin_note": "Frau Wittwer — S/4 CO Greenfield mit UPA und Material Ledger ist knapp. Ich biete ein Arbeitspaket: €1.100/Tag, 3 Monate, Greenfield-Referenz. Wenn verhandlungssicheres Deutsch Pflicht ist und ich das Profil nicht habe, sage ich es in der ersten Minute. Kein CV ohne Tagessatz. — [Your name], SAP Desk",
        "email_subject": "S/4 CO Greenfield — Arbeitspaket €1.100/Tag, nicht 15 CVs",
        "email_body": "Guten Tag Frau Wittwer,\n\nS/4HANA CO Greenfield (UPA, Material Ledger, Margin Analysis, Produktkosten).\n\nAngebot: ein benannter CO-Berater, €1.100 / Tag, drei Monate Mindestlaufzeit. Profil erst nach Bestätigung von Deutsch-Pflicht und Tagessatzband.\n\nIst Deutsch verhandlungssicher zwingend? Wenn ja und das Profil es nicht erfüllt, spare ich uns beide die Schleife.\n\nMit freundlichen Grüßen\n[Your name]\nSAP Desk\n[Mobile]",
        "followup_2": "CO-Greenfield mit UPA bleibt knapp. €1.100/Tag steht. Deutsch ja/nein — dann sende ich das eine Profil.",
        "followup_3": "Akte zu. Wenn der CO-Stream ohne Besetzung in den Realisierungsstart geht, diese Mail reicht als Anker.",
        "call_opener": "UPA und Material Ledger sind der Engpass, nicht 'ein CO-Berater'. €1.100/Tag. Ist Deutsch ein Knock-out?",
    },
    "P014": {
        "margin": "later",
        "gross": "good if still open; listing may be stale",
        "product": "arbeitspaket",
        "talk_to": "Corporate Connect — confirm the mandate is live before pricing",
        "price_anchor": "€850/day independent PMO at 50–60%",
        "linkedin_note": "PMO Brownfield Düsseldorf — falls das Mandat noch lebt: unabhängiges PMO €850/Tag bei 50–60%, nicht als verlängerter Arm des Beratungshauses. Erst bestätigen ob offen, dann Profil. — [Your name]",
        "email_subject": "S/4 PMO Düsseldorf — noch offen? Dann €850/Tag, unabhängig",
        "email_body": "Hallo,\n\nInterim-PMO für S/4 Brownfield, Mittelstand, remote, ~50–60%.\n\nWenn das Mandat noch vakant ist: €850 / Tag, unabhängig vom Implementierungspartner, 3 Monate. Wenn ihr inzwischen SIT/Cutover braucht, anderes Arbeitspaket.\n\nLebt die Anfrage noch?\n\nMit freundlichen Grüßen\n[Your name] | SAP Desk",
        "followup_2": "Nur eine Frage: Mandat tot oder lebend? Wenn lebend, steht €850.",
        "followup_3": "Ich gehe von 'besetzt' aus.",
        "call_opener": "Ist das PMO noch unbesetzt? Wenn ja, €850/Tag unabhängig. Wenn nein, braucht ihr SIT?",
    },
    "P015": {
        "margin": "later",
        "gross": "boutique can pay DE freelance rates — only then",
        "product": "arbeitspaket",
        "talk_to": "Geschäftsführung / recruiting lead at neoimpulse",
        "price_anchor": "€1,000/day freelance SD or walk from perm",
        "linkedin_people_override": "https://www.linkedin.com/search/results/people/?keywords=neoimpulse%20(Geschäftsführung%20OR%20Founder%20OR%20SAP)",
        "linkedin_note": "neoimpulse sucht Senior SD S/4. Bei 40 Leuten ist eine offene SD-Stelle oft ein verkauftes Projekt. Ich biete Freelance €1.000/Tag für 3 Monate, nicht Festanstellung. Wenn ihr nur perm sucht, unnötig. — [Your name], SAP Desk",
        "email_subject": "neoimpulse SD — €1.000/Tag freelance, kein perm",
        "email_body": "Hallo,\n\n(Senior) SAP SD S/4 / Supply Chain.\n\nIch stelle kein perm-Profil. Angebot: Freelance, €1.000 / Tag, 3 Monate, OTC + FI-Nähe. Wenn das Projekt schon verkauft und der Sitz leer ist, lohnt ein 15-Minuten-Gespräch.\n\nMit freundlichen Grüßen\n[Your name] | SAP Desk",
        "followup_2": "Nur Freelance €1.000/Tag. Perm-Trichter lasse ich.",
        "followup_3": "Akte zu.",
        "call_opener": "Ist der SD-Sitz für ein verkauftes Projekt leer? Dann €1.000/Tag. Sonst nicht.",
    },
    "P016": {
        "margin": "skip",
        "gross": "volume SI, MSP rates",
        "product": "arbeitspaket",
        "talk_to": "skip",
        "price_anchor": "skip",
        "linkedin_note": "SKIP — Nagarro DACH volume. Empanelment theatre.",
        "email_subject": "SKIP",
        "email_body": "Do not send.",
        "followup_2": "",
        "followup_3": "",
        "call_opener": "",
    },
    "P017": {
        "margin": "skip",
        "gross": "Big Four vendor cycle",
        "product": "arbeitspaket",
        "talk_to": "skip",
        "price_anchor": "skip",
        "linkedin_note": "SKIP — PwC empanelment is a 2027 project.",
        "email_subject": "SKIP",
        "email_body": "Do not send.",
        "followup_2": "",
        "followup_3": "",
        "call_opener": "",
        },
    "P018": {
        "margin": "later",
        "gross": "only freelance architect at €1,150+",
        "product": "arbeitspaket",
        "talk_to": "cbs recruiting / integration practice lead",
        "price_anchor": "€1,150/day Clean Core integration architect",
        "linkedin_note": "cbs sucht S/4 Integration Architect. Ich biete Freelance €1.150/Tag (AIF, Integration Suite, Clean Core), kein Fest. Ein Profil nach Tagessatz-OK. — [Your name]",
        "email_subject": "cbs Integration — €1.150/Tag Freelance Architect",
        "email_body": "Hallo,\n\nSenior Consultant / Architect S/4HANA Integration.\n\nAngebot: Freelance, €1.150 / Tag, AIF / OData / Integration Suite / Clean Core. Kein perm. Profil nach Bestätigung des Satzes.\n\nMit freundlichen Grüßen\n[Your name] | SAP Desk",
        "followup_2": "Nur €1.150 Freelance. Sonst nicht.",
        "followup_3": "Akte zu.",
        "call_opener": "Integration Architect als Freelance zu €1.150 — oder sucht ihr nur fest?",
    },
    "P019": {
        "margin": "send",
        "gross": "25–40% on senior remote SD",
        "product": "arbeitspaket",
        "talk_to": "TalentCloud consultant who owns the life-science client",
        "price_anchor": "€1,050/day senior SD, CET, through Dec 2026",
        "linkedin_note": "Your remote Senior SD S/4 (EU template + site, CET, through Dec 2026) is an Arbeitspaket. I price €1,050/day, named consultant, no CV shotgun. Is the mandate still open and what is the client rate cap? 15 min. — [Your name], SAP Desk",
        "email_subject": "Senior SD S/4 remote — €1,050/day named, not a CV pack",
        "email_body": "Hello,\n\nSenior SAP SD S/4 remote, European template rollout, CET 09:00–17:30, to December 2026.\n\nI do not send a pile of CVs. Offer: one named senior SD, €1,050 / day. Tell me the client cap and whether the start slipped. Then you get the profile.\n\nRegards,\n[Your name] | SAP Desk\n[Mobile]",
        "followup_2": "If the life-science site rollout is still short an SD, €1,050/day is the number. Cap — what is it?",
        "followup_3": "Assuming filled. Reply with the cap if it reopens.",
        "call_opener": "One number: €1,050/day for a named senior SD on CET. What is the client cap, and is the seat empty?",
    },
    "P020": {
        "margin": "send",
        "gross": "25–40% on OTC freelance",
        "product": "arbeitspaket",
        "talk_to": "Elvis Eckardt — then the fashion-retail SAP owner",
        "price_anchor": "€1,000/day SD/OTC, 3 months remote, peak-season second seat if first is filled",
        "linkedin_note": "Fashion retail S/4 SD/OTC freelance from 1 Sep — if that seat filled, they often still need a second SD for peak. €1,000/day, named, remote. I will not bid blind. Open or not? — [Your name], SAP Desk",
        "email_subject": "Fashion OTC — €1,000/day named SD, seat 1 or seat 2",
        "email_body": "Hello,\n\nSAP SD / OTC S/4, fashion retail / e-commerce, remote, 3 months.\n\nIf seat one is filled, ask the client about a second SD for peak. Offer: €1,000 / day, named consultant. Confirm open / rate cap, then I send one profile.\n\nRegards,\n[Your name] | SAP Desk\n[Mobile]",
        "followup_2": "Peak season is the margin. Second SD at €1,000/day — do they want it?",
        "followup_3": "Closing. Reply 'peak' if they panic in October.",
        "call_opener": "Seat filled or not? If filled, I am selling the second OTC for peak at €1,000/day. If empty, same number for seat one.",
    },
    "P021": {
        "margin": "skip",
        "gross": "perm SI",
        "product": "arbeitspaket",
        "talk_to": "skip",
        "price_anchor": "skip",
        "linkedin_note": "SKIP — Convista perm MM.",
        "email_subject": "SKIP",
        "email_body": "Do not send.",
        "followup_2": "",
        "followup_3": "",
        "call_opener": "",
    },
    "P022": {
        "margin": "skip",
        "gross": "perm SI",
        "product": "arbeitspaket",
        "talk_to": "skip",
        "price_anchor": "skip",
        "linkedin_note": "SKIP — Innovabee perm PP.",
        "email_subject": "SKIP",
        "email_body": "Do not send.",
        "followup_2": "",
        "followup_3": "",
        "call_opener": "",
    },
}


def main() -> None:
    bundle = json.loads(CURATED.read_text(encoding="utf-8"))
    bundle["agency"] = AGENCY
    bundle["strategy"] = STRATEGY
    bundle["generated_at"] = "2026-09-04"
    for row in bundle["prospects"]:
        extra = OVERLAYS.get(row["id"])
        if not extra:
            continue
        row.update(extra)
        override = extra.get("linkedin_people_override")
        if override:
            row.setdefault("urls", {})["linkedin_people"] = override
        row.pop("linkedin_people_override", None)
        if extra.get("margin") == "skip":
            row["heat"] = "warm"
    CURATED.write_text(json.dumps(bundle, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    send = [p["id"] for p in bundle["prospects"] if p.get("margin") == "send"]
    print("Updated", CURATED)
    print("Send now:", ", ".join(send))


if __name__ == "__main__":
    main()
